@apiUrl = http://localhost:3001/api

###

# @name getPersons
GET {{apiUrl}}/persons

###

# @name getPerson
@personId = 5d133ffbde59155307fc15cd
GET {{apiUrl}}/persons/{{personId}}

###

# @name postPerson
POST {{apiUrl}}/persons
Content-Type: application/json

{
  "name": "Charles Changed",
  "number": "300"
}

###

# @name putPerson
PUT {{apiUrl}}/persons/{{personId}}
Content-Type: application/json

{
  "name": "Charles Changed",
  "number": "200"
}

###

# @name deletePerson
DELETE {{apiUrl}}/persons/{{personId}}

###

# @name postPersonFail
POST {{apiUrl}}/persons
Content-Type: application/json

{
  "name": "Test Person"
}

###

# @name info
GET http://localhost:3001/info

###

# @name endpointFail
GET {{apiUrl}}/wrongendpoint
