@apiUrl = http://localhost:3001/api

###

# @name getPersons
GET {{apiUrl}}/persons

###

# @name getPerson
@personId = 5d1326438e3f73487b9ba465
GET {{apiUrl}}/persons/{{personId}}

###

# @name postPerson
POST {{apiUrl}}/persons
Content-Type: application/json

{
  "name": "Rest Test",
  "number": "200"
}

###

# @name deletePerson
DELETE {{apiUrl}}/persons/{{personId}}

###

# @name postPersonFail
POST {{apiUrl}}/persons
Content-Type: application/json

{
  "name": "Test Person"
}

###

# @name endpointFail
GET {{apiUrl}}/wrongendpoint
